---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18

platforms:
  - name: centos-7.1
  - name: ubuntu-14.04
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2

suites:
  - name: java_se_test
    run_list:
      - recipe[java_se::default]
    attributes:
