language: ruby

rvm:
  - 2.1.7

os: osx
  - osx_image: xcode8
  - osx_image: xcode7.3
  - osx_image: xcode7.2
  - osx_image: xcode7.1
  - osx_image: xcode7
  - osx_image: xcode6.4
  - osx_image: beta-xcode6.3
  - osx_image: beta-xcode6.2
#    - osx_image: beta-xcode6.1

sudo: required

script:
  - KITCHEN_YAML=.kitchen.localhost.yml bundle exec kitchen verify macosx

branches:
  only:
  - macosx
