language: ruby

rvm:
  - 2.1.7

os: osx

osx_image:
  - xcode8
  - xcode7.3
  - xcode7.2
  - xcode7.1
  - xcode7
  - xcode6.4
  - beta-xcode6.3
  - beta-xcode6.2
  - beta-xcode6.1

sudo: required

script:
  - KITCHEN_YAML=.kitchen.localhost.yml bundle exec kitchen verify macosx

branches:
  only:
  - macosx
