version: "master-{build}"

os: Windows Server 2012 R2
platform:
  - x64

cache:
  - vendor/bundle

environment:
  KITCHEN_YAML: .kitchen.localhost.yml
  matrix:
    - RUBY_VERSION: 21

clone_folder: c:\projects\kitchen-machine
clone_depth: 1

branches:
  only:
    - master

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

build_script:
  - bundle exec rake

test_script:
  - bundle exec kitchen verify windows
