version: "master-{build}"

os: Windows Server 2012 R2
platform:
  - x64

environment:
  matrix:
    - ruby_version: "21"

clone_folder: c:\projects\kitchen-machine
clone_depth: 1

branches:
  only:
    - master

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - KITCHEN_YAML=.kitchen.localhost.yml bundle exec kitchen verify windows
