version: "master-{build}"

os: Windows Server 2012 R2
platform:
  - x64

cache:
  - '%TEMP%\verifier\gems'

install:
  - cinst chefdk
  - SET PATH=C:\opscode\chefdk\bin;%PATH%

build_script:
  - chef exec bundle update

test_script:
  - chef exec bundle exec kitchen test

branches:
  only:
    - master
